# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.9/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.9/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jejikeh/code/breakout

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jejikeh/code/breakout

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.9/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.9/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jejikeh/code/breakout/CMakeFiles /Users/jejikeh/code/breakout//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jejikeh/code/breakout/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named Arkanoid

# Build rule for target.
Arkanoid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Arkanoid
.PHONY : Arkanoid

# fast build rule for target.
Arkanoid/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/build
.PHONY : Arkanoid/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f glfw_binary/src/CMakeFiles/glfw.dir/build.make glfw_binary/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

glfw-3.3.3/deps/glad_gl.o: glfw-3.3.3/deps/glad_gl.c.o
.PHONY : glfw-3.3.3/deps/glad_gl.o

# target to build an object file
glfw-3.3.3/deps/glad_gl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glfw-3.3.3/deps/glad_gl.c.o
.PHONY : glfw-3.3.3/deps/glad_gl.c.o

glfw-3.3.3/deps/glad_gl.i: glfw-3.3.3/deps/glad_gl.c.i
.PHONY : glfw-3.3.3/deps/glad_gl.i

# target to preprocess a source file
glfw-3.3.3/deps/glad_gl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glfw-3.3.3/deps/glad_gl.c.i
.PHONY : glfw-3.3.3/deps/glad_gl.c.i

glfw-3.3.3/deps/glad_gl.s: glfw-3.3.3/deps/glad_gl.c.s
.PHONY : glfw-3.3.3/deps/glad_gl.s

# target to generate assembly for a file
glfw-3.3.3/deps/glad_gl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glfw-3.3.3/deps/glad_gl.c.s
.PHONY : glfw-3.3.3/deps/glad_gl.c.s

imgui-1.90.5/backends/imgui_impl_glfw.o: imgui-1.90.5/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui-1.90.5/backends/imgui_impl_glfw.o

# target to build an object file
imgui-1.90.5/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui-1.90.5/backends/imgui_impl_glfw.cpp.o

imgui-1.90.5/backends/imgui_impl_glfw.i: imgui-1.90.5/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui-1.90.5/backends/imgui_impl_glfw.i

# target to preprocess a source file
imgui-1.90.5/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui-1.90.5/backends/imgui_impl_glfw.cpp.i

imgui-1.90.5/backends/imgui_impl_glfw.s: imgui-1.90.5/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui-1.90.5/backends/imgui_impl_glfw.s

# target to generate assembly for a file
imgui-1.90.5/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui-1.90.5/backends/imgui_impl_glfw.cpp.s

imgui-1.90.5/backends/imgui_impl_opengl3.o: imgui-1.90.5/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui-1.90.5/backends/imgui_impl_opengl3.o

# target to build an object file
imgui-1.90.5/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui-1.90.5/backends/imgui_impl_opengl3.cpp.o

imgui-1.90.5/backends/imgui_impl_opengl3.i: imgui-1.90.5/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui-1.90.5/backends/imgui_impl_opengl3.i

# target to preprocess a source file
imgui-1.90.5/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui-1.90.5/backends/imgui_impl_opengl3.cpp.i

imgui-1.90.5/backends/imgui_impl_opengl3.s: imgui-1.90.5/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui-1.90.5/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
imgui-1.90.5/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui-1.90.5/backends/imgui_impl_opengl3.cpp.s

imgui-1.90.5/imgui.o: imgui-1.90.5/imgui.cpp.o
.PHONY : imgui-1.90.5/imgui.o

# target to build an object file
imgui-1.90.5/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui.cpp.o
.PHONY : imgui-1.90.5/imgui.cpp.o

imgui-1.90.5/imgui.i: imgui-1.90.5/imgui.cpp.i
.PHONY : imgui-1.90.5/imgui.i

# target to preprocess a source file
imgui-1.90.5/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui.cpp.i
.PHONY : imgui-1.90.5/imgui.cpp.i

imgui-1.90.5/imgui.s: imgui-1.90.5/imgui.cpp.s
.PHONY : imgui-1.90.5/imgui.s

# target to generate assembly for a file
imgui-1.90.5/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui.cpp.s
.PHONY : imgui-1.90.5/imgui.cpp.s

imgui-1.90.5/imgui_demo.o: imgui-1.90.5/imgui_demo.cpp.o
.PHONY : imgui-1.90.5/imgui_demo.o

# target to build an object file
imgui-1.90.5/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_demo.cpp.o
.PHONY : imgui-1.90.5/imgui_demo.cpp.o

imgui-1.90.5/imgui_demo.i: imgui-1.90.5/imgui_demo.cpp.i
.PHONY : imgui-1.90.5/imgui_demo.i

# target to preprocess a source file
imgui-1.90.5/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_demo.cpp.i
.PHONY : imgui-1.90.5/imgui_demo.cpp.i

imgui-1.90.5/imgui_demo.s: imgui-1.90.5/imgui_demo.cpp.s
.PHONY : imgui-1.90.5/imgui_demo.s

# target to generate assembly for a file
imgui-1.90.5/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_demo.cpp.s
.PHONY : imgui-1.90.5/imgui_demo.cpp.s

imgui-1.90.5/imgui_draw.o: imgui-1.90.5/imgui_draw.cpp.o
.PHONY : imgui-1.90.5/imgui_draw.o

# target to build an object file
imgui-1.90.5/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_draw.cpp.o
.PHONY : imgui-1.90.5/imgui_draw.cpp.o

imgui-1.90.5/imgui_draw.i: imgui-1.90.5/imgui_draw.cpp.i
.PHONY : imgui-1.90.5/imgui_draw.i

# target to preprocess a source file
imgui-1.90.5/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_draw.cpp.i
.PHONY : imgui-1.90.5/imgui_draw.cpp.i

imgui-1.90.5/imgui_draw.s: imgui-1.90.5/imgui_draw.cpp.s
.PHONY : imgui-1.90.5/imgui_draw.s

# target to generate assembly for a file
imgui-1.90.5/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_draw.cpp.s
.PHONY : imgui-1.90.5/imgui_draw.cpp.s

imgui-1.90.5/imgui_tables.o: imgui-1.90.5/imgui_tables.cpp.o
.PHONY : imgui-1.90.5/imgui_tables.o

# target to build an object file
imgui-1.90.5/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_tables.cpp.o
.PHONY : imgui-1.90.5/imgui_tables.cpp.o

imgui-1.90.5/imgui_tables.i: imgui-1.90.5/imgui_tables.cpp.i
.PHONY : imgui-1.90.5/imgui_tables.i

# target to preprocess a source file
imgui-1.90.5/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_tables.cpp.i
.PHONY : imgui-1.90.5/imgui_tables.cpp.i

imgui-1.90.5/imgui_tables.s: imgui-1.90.5/imgui_tables.cpp.s
.PHONY : imgui-1.90.5/imgui_tables.s

# target to generate assembly for a file
imgui-1.90.5/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_tables.cpp.s
.PHONY : imgui-1.90.5/imgui_tables.cpp.s

imgui-1.90.5/imgui_widgets.o: imgui-1.90.5/imgui_widgets.cpp.o
.PHONY : imgui-1.90.5/imgui_widgets.o

# target to build an object file
imgui-1.90.5/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_widgets.cpp.o
.PHONY : imgui-1.90.5/imgui_widgets.cpp.o

imgui-1.90.5/imgui_widgets.i: imgui-1.90.5/imgui_widgets.cpp.i
.PHONY : imgui-1.90.5/imgui_widgets.i

# target to preprocess a source file
imgui-1.90.5/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_widgets.cpp.i
.PHONY : imgui-1.90.5/imgui_widgets.cpp.i

imgui-1.90.5/imgui_widgets.s: imgui-1.90.5/imgui_widgets.cpp.s
.PHONY : imgui-1.90.5/imgui_widgets.s

# target to generate assembly for a file
imgui-1.90.5/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui-1.90.5/imgui_widgets.cpp.s
.PHONY : imgui-1.90.5/imgui_widgets.cpp.s

src/arkanoid_impl.o: src/arkanoid_impl.cpp.o
.PHONY : src/arkanoid_impl.o

# target to build an object file
src/arkanoid_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/arkanoid_impl.cpp.o
.PHONY : src/arkanoid_impl.cpp.o

src/arkanoid_impl.i: src/arkanoid_impl.cpp.i
.PHONY : src/arkanoid_impl.i

# target to preprocess a source file
src/arkanoid_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/arkanoid_impl.cpp.i
.PHONY : src/arkanoid_impl.cpp.i

src/arkanoid_impl.s: src/arkanoid_impl.cpp.s
.PHONY : src/arkanoid_impl.s

# target to generate assembly for a file
src/arkanoid_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/arkanoid_impl.cpp.s
.PHONY : src/arkanoid_impl.cpp.s

src/entities/ball.o: src/entities/ball.cpp.o
.PHONY : src/entities/ball.o

# target to build an object file
src/entities/ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/entities/ball.cpp.o
.PHONY : src/entities/ball.cpp.o

src/entities/ball.i: src/entities/ball.cpp.i
.PHONY : src/entities/ball.i

# target to preprocess a source file
src/entities/ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/entities/ball.cpp.i
.PHONY : src/entities/ball.cpp.i

src/entities/ball.s: src/entities/ball.cpp.s
.PHONY : src/entities/ball.s

# target to generate assembly for a file
src/entities/ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/entities/ball.cpp.s
.PHONY : src/entities/ball.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/render_impl_gl.o: src/render_impl_gl.cpp.o
.PHONY : src/render_impl_gl.o

# target to build an object file
src/render_impl_gl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/render_impl_gl.cpp.o
.PHONY : src/render_impl_gl.cpp.o

src/render_impl_gl.i: src/render_impl_gl.cpp.i
.PHONY : src/render_impl_gl.i

# target to preprocess a source file
src/render_impl_gl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/render_impl_gl.cpp.i
.PHONY : src/render_impl_gl.cpp.i

src/render_impl_gl.s: src/render_impl_gl.cpp.s
.PHONY : src/render_impl_gl.s

# target to generate assembly for a file
src/render_impl_gl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arkanoid.dir/build.make CMakeFiles/Arkanoid.dir/src/render_impl_gl.cpp.s
.PHONY : src/render_impl_gl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Arkanoid"
	@echo "... glad"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... glfw-3.3.3/deps/glad_gl.o"
	@echo "... glfw-3.3.3/deps/glad_gl.i"
	@echo "... glfw-3.3.3/deps/glad_gl.s"
	@echo "... imgui-1.90.5/backends/imgui_impl_glfw.o"
	@echo "... imgui-1.90.5/backends/imgui_impl_glfw.i"
	@echo "... imgui-1.90.5/backends/imgui_impl_glfw.s"
	@echo "... imgui-1.90.5/backends/imgui_impl_opengl3.o"
	@echo "... imgui-1.90.5/backends/imgui_impl_opengl3.i"
	@echo "... imgui-1.90.5/backends/imgui_impl_opengl3.s"
	@echo "... imgui-1.90.5/imgui.o"
	@echo "... imgui-1.90.5/imgui.i"
	@echo "... imgui-1.90.5/imgui.s"
	@echo "... imgui-1.90.5/imgui_demo.o"
	@echo "... imgui-1.90.5/imgui_demo.i"
	@echo "... imgui-1.90.5/imgui_demo.s"
	@echo "... imgui-1.90.5/imgui_draw.o"
	@echo "... imgui-1.90.5/imgui_draw.i"
	@echo "... imgui-1.90.5/imgui_draw.s"
	@echo "... imgui-1.90.5/imgui_tables.o"
	@echo "... imgui-1.90.5/imgui_tables.i"
	@echo "... imgui-1.90.5/imgui_tables.s"
	@echo "... imgui-1.90.5/imgui_widgets.o"
	@echo "... imgui-1.90.5/imgui_widgets.i"
	@echo "... imgui-1.90.5/imgui_widgets.s"
	@echo "... src/arkanoid_impl.o"
	@echo "... src/arkanoid_impl.i"
	@echo "... src/arkanoid_impl.s"
	@echo "... src/entities/ball.o"
	@echo "... src/entities/ball.i"
	@echo "... src/entities/ball.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/render_impl_gl.o"
	@echo "... src/render_impl_gl.i"
	@echo "... src/render_impl_gl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

